# Does not work from scratch,
# Need to determine the missing dependencies
#FROM scratch

FROM alpine:3.7

MAINTAINER Clint Armstrong <carmstrong@trilliumit.com>

ADD ./build /

ENTRYPOINT ["/docker-vxlan-plugin"]
